use super::{Email, EmailId, Mailbox};

pub fn mock_emails() -> Vec<Email> {
    vec![
        email(
            1,
            "John Smith",
            "john@example.com",
            "Project Update",
            "Here's the latest update on the project. The revised timeline is ready for review.",
            "Today, 10:42 AM",
            "10:42 AM",
            Mailbox::Inbox,
            true,
            true,
            Some("project"),
            vec![
                "Hey,",
                "Here's the latest update on the project. The revised timeline is ready for review, and the implementation risk is now concentrated in the data migration window.",
                "I've attached the latest version for you to look through. The parts I would most appreciate feedback on are the rollout sequence and the fallback behavior if the index rebuild takes longer than expected.",
                "Thanks,\nJohn",
            ],
        ),
        email(
            2,
            "Sarah Jones",
            "sarah@example.com",
            "Meeting Tomorrow",
            "Are you available for the meeting tomorrow? I moved it to 2:30 PM.",
            "Yesterday",
            "Yesterday",
            Mailbox::Inbox,
            true,
            false,
            None,
            vec![
                "Hi,",
                "Are you available for the meeting tomorrow? I moved it to 2:30 PM so the design team can join after their review.",
                "The agenda is short: launch checklist, open questions, and ownership for the final week. No prep is required beyond skimming the updated project note.",
                "Best,\nSarah",
            ],
        ),
        email(
            3,
            "GitHub",
            "notifications@github.com",
            "New pull request",
            "Someone opened a pull request that improves keyboard navigation in the tab bar.",
            "Sep 24",
            "Sep 24",
            Mailbox::Inbox,
            true,
            false,
            Some("dev"),
            vec![
                "A new pull request is ready for review.",
                "This change improves keyboard navigation in the tab bar, adds visible focus states, and introduces a regression test for wrapping between the first and last tabs.",
                "View the diff and leave feedback directly on the pull request.",
            ],
        ),
        email(
            4,
            "Maya Chen",
            "maya@example.com",
            "Design review notes",
            "I cleaned up the interaction notes and highlighted the two places where focus gets ambiguous.",
            "Sep 24",
            "Sep 24",
            Mailbox::Inbox,
            false,
            true,
            Some("design"),
            vec![
                "I went through the prototype again this morning. The horizontal navigation reads well and keeps the message list feeling like the main surface.",
                "The two areas that need another pass are tab overflow and the selected mailbox state. Both should remain understandable without relying on color alone.",
                "I added the notes to the review document.",
                "Maya",
            ],
        ),
        email(
            5,
            "Finance",
            "billing@example.com",
            "Invoice #294",
            "Your monthly invoice is ready. The next billing cycle begins on October 1.",
            "Sep 23",
            "Sep 23",
            Mailbox::Inbox,
            false,
            false,
            Some("finance"),
            vec![
                "Hello,",
                "Your monthly invoice is ready. The next billing cycle begins on October 1 and no action is required.",
                "The invoice covers the team plan through September 30. Please use account ID 8841 when contacting support with a billing question.",
                "Finance",
            ],
        ),
        email(
            6,
            "Noah Williams",
            "noah@example.com",
            "Build passed on Linux",
            "The Wayland build is green again after updating the native text input dependency.",
            "Sep 22",
            "Sep 22",
            Mailbox::Inbox,
            false,
            false,
            Some("dev"),
            vec![
                "The Wayland build is green again after updating the native text input dependency.",
                "I also checked resize behavior at 1x and 2x scale. Nothing clips after the minimum window size is introduced.",
                "Noah",
            ],
        ),
        email(
            7,
            "Aisha Patel",
            "aisha@example.com",
            "Quarterly planning",
            "Here is the first pass at the planning outline. I kept the open questions in place rather than guessing.",
            "Sep 21",
            "Sep 21",
            Mailbox::Inbox,
            false,
            true,
            Some("planning"),
            vec![
                "Here is the first pass at the planning outline. I kept the open questions in place rather than guessing.",
                "The largest decision is whether we invest in another synchronization pass or use the current window to improve everyday navigation. My recommendation is the latter.",
                "Comments are welcome before Thursday.",
                "Aisha",
            ],
        ),
        email(
            8,
            "Linear",
            "updates@linear.app",
            "NOR-184 moved to In Review",
            "Keyboard navigation and focus restoration moved to In Review.",
            "Sep 20",
            "Sep 20",
            Mailbox::Inbox,
            false,
            false,
            Some("dev"),
            vec![
                "NOR-184 moved to In Review.",
                "Keyboard navigation and focus restoration are implemented. The remaining item is runtime verification with an IME and a screen reader.",
                "Open issue",
            ],
        ),
        email(
            9,
            "Elena Rossi",
            "elena@example.com",
            "Research interview summary",
            "Three participants returned to the editor tab model after seeing the prototype.",
            "Sep 19",
            "Sep 19",
            Mailbox::Inbox,
            false,
            false,
            Some("research"),
            vec![
                "Three participants returned to the editor tab model after seeing the prototype.",
                "They valued the persistent horizontal structure, but two people expected a way to see more tab titles at once. We should test narrower variable-width tabs next.",
                "The full summary and clips are in the research folder.",
                "Elena",
            ],
        ),
        email(
            10,
            "Security",
            "security@example.com",
            "New sign-in from Firefox on Linux",
            "A new sign-in was detected from Firefox on Linux at 9:14 AM.",
            "Sep 18",
            "Sep 18",
            Mailbox::Inbox,
            false,
            false,
            Some("security"),
            vec![
                "A new sign-in was detected from Firefox on Linux at 9:14 AM.",
                "If this was you, no action is needed. If you do not recognize the activity, review your active sessions and rotate your credentials.",
            ],
        ),
        email(
            11,
            "Tom Becker",
            "tom@example.com",
            "Lunch on Friday?",
            "There is a new ramen place near the office. Are you interested in going on Friday?",
            "Sep 17",
            "Sep 17",
            Mailbox::Inbox,
            false,
            false,
            None,
            vec![
                "There is a new ramen place near the office. Are you interested in going on Friday?",
                "I can reserve a table around 12:30 if the group is small enough.",
                "Tom",
            ],
        ),
        email(
            12,
            "Calendar",
            "calendar@example.com",
            "Invitation: Weekly product review",
            "Your weekly product review starts Friday at 10:00 AM.",
            "Sep 16",
            "Sep 16",
            Mailbox::Inbox,
            false,
            false,
            Some("calendar"),
            vec![
                "Your weekly product review starts Friday at 10:00 AM and ends at 10:45 AM.",
                "Agenda: product risks, decisions needed, and a short update on the email client prototype.",
            ],
        ),
        email(
            13,
            "You",
            "me@example.com",
            "Re: API naming",
            "I left a few comments on the endpoint names and added the migration examples.",
            "Sep 22",
            "Sep 22",
            Mailbox::Sent,
            false,
            false,
            None,
            vec![
                "I left a few comments on the endpoint names and added the migration examples.",
                "The important part is keeping the existing identifiers stable while the new surface settles.",
            ],
        ),
        email(
            14,
            "You",
            "me@example.com",
            "September notes",
            "A short summary of decisions, open questions, and follow-ups for next week.",
            "Sep 15",
            "Sep 15",
            Mailbox::Sent,
            false,
            false,
            None,
            vec![
                "A short summary of decisions, open questions, and follow-ups for next week.",
                "The main decision was to keep this phase UI-only and validate the interaction model before introducing any mail transport.",
            ],
        ),
        email(
            15,
            "You",
            "me@example.com",
            "Prototype follow-ups",
            "Capture the focus order and test the tab bar with longer subject lines.",
            "Sep 12",
            "Sep 12",
            Mailbox::Drafts,
            false,
            false,
            None,
            vec![
                "Capture the focus order and test the tab bar with longer subject lines.",
                "Also verify the search overlay with the keyboard before sharing the prototype.",
            ],
        ),
        email(
            16,
            "You",
            "me@example.com",
            "Weekly notes",
            "Turn the open questions into a short checklist for the next review.",
            "Sep 8",
            "Sep 8",
            Mailbox::Drafts,
            false,
            false,
            None,
            vec!["Turn the open questions into a short checklist for the next review."],
        ),
        email(
            17,
            "GitHub",
            "notifications@github.com",
            "Release checklist completed",
            "The archived prototype checklist has been completed for the previous iteration.",
            "Aug 29",
            "Aug 29",
            Mailbox::Archive,
            false,
            false,
            Some("release"),
            vec![
                "The archived prototype checklist has been completed for the previous iteration.",
                "This thread is kept for reference and is no longer active.",
            ],
        ),
        email(
            18,
            "Old Projects",
            "projects@example.com",
            "Expired project notification",
            "This is an old notification retained to demonstrate the trash view.",
            "Aug 12",
            "Aug 12",
            Mailbox::Trash,
            false,
            false,
            None,
            vec!["This is an old notification retained to demonstrate the trash view."],
        ),
    ]
}

#[allow(clippy::too_many_arguments)]
fn email(
    id: u16,
    sender: &str,
    address: &str,
    subject: &str,
    preview: &str,
    full_date: &str,
    timestamp: &str,
    mailbox: Mailbox,
    unread: bool,
    starred: bool,
    label: Option<&str>,
    body: Vec<&str>,
) -> Email {
    Email {
        id: EmailId(id),
        sender: sender.to_string(),
        address: address.to_string(),
        recipients: if mailbox == Mailbox::Sent || mailbox == Mailbox::Drafts {
            vec!["sam@example.com".to_string()]
        } else {
            vec!["me@example.com".to_string()]
        },
        subject: subject.to_string(),
        preview: preview.to_string(),
        body: body
            .iter()
            .map(|paragraph| (*paragraph).to_string())
            .collect(),
        timestamp: timestamp.to_string(),
        full_date: full_date.to_string(),
        mailbox,
        unread,
        starred,
        pinned: false,
        label: label.map(str::to_string),
    }
}
